app/playlist/routes.py
from types import DynamicClassAttribute
from flask import Blueprint, render_template, url_for, redirect, request, flash
from app import playlist
from flask_login import current_user


playlist = Blueprint("playlist", __name__)
from .. import deezer_client
from ..forms import SearchForm, SearchSongForm, FavoritePlaylistForm, CreatePlaylistForm
from ..models import Playlist
from ..utils import current_time

import io
import base64

@playlist.route("/", methods=["GET", "POST"])
def index():
    form = SearchForm()

    if form.validate_on_submit():
        print("HERE")
        return redirect(url_for("playlist.query_results", query=form.search_query.data))

    return render_template("index.html", form=form)

@playlist.route("/create", methods=["GET", "POST"])
def create():
    form = CreatePlaylistForm()

    if form.validate_on_submit() and current_user.is_authenticated:
        playlist = Playlist(
            author = current_user._get_current_object(),
            title = form.title.data,
            description = form.description.data,
            date = current_time(),
        )
        playlist.save()
        return redirect(request.path)

    return render_template("create_playlist.html", form=form)
    
    

@playlist.route("/playlist-results/<query>", methods=["GET"])
def query_results(query):
    try:
        results = Playlist.objects.search_text(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("playlist.index"))

    return render_template("playlistquery.html", results=results)

@playlist.route("/playlist/<curr_playlist>/song-results/<query>", methods=["GET"])
def song_results(curr_playlist, query):
    try:
        results = deezer_client.search(query)
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("songs.index"))

    return render_template("query.html", results=results, playlist_id=curr_playlist)

#Displays playlist and gives user option to favorite
@playlist.route("/playlist/<playlist_id>", methods=["GET", "POST"])
def playlist_detail(playlist_id):
    try:
        playlist = Playlist.objects(id=playlist_id).first()
    except ValueError as e:
        flash(str(e))
        return redirect(url_for("playlist.index"))

    count = len(playlist.songs)

    favorite = FavoritePlaylistForm()
    if favorite.validate_on_submit() and current_user.is_authenticated:
        user = current_user._get_current_object()
        user.favorites.append(playlist)
        user.save()
        return redirect(request.path)    
        
    return render_template("playlist_detail.html", playlist=playlist, favorite=favorite, count=count)

#Edit Playlist Add/Remove Songs, edit playlist title,bio, and picture
@playlist.route("/editplaylist/<playlist_id>", methods=["GET", "POST"])
def edit_playlist(playlist_id):

    playlist = Playlist.objects(id=playlist_id).first()

    if current_user.username != playlist.author.username:
        return redirect(url_for("playlist.index"))
    form = SearchSongForm()

    if form.validate_on_submit():
        return redirect(url_for("playlist.song_results", query=form.search_query.data, curr_playlist=playlist_id))

    return render_template("edit_playlist.html", form=form, playlist_id=playlist_id)

@playlist.route('/playlist/<playlist_id>/add/<song_id>/')
def add_song(playlist_id, song_id):
    song = deezer_client.retrieve_song_by_id(song_id)


    playlist = Playlist.objects(id=playlist_id).first()
    playlist.songs.append(vars(song))
    playlist.save()

    return redirect(url_for('playlist.edit_playlist', playlist_id=playlist_id))

app/users/routes.py
from flask import Blueprint, redirect, url_for, render_template, flash, request
from app import playlist
from flask_mail import Mail,Message# stdlib
from flask_login import current_user, login_required, login_user, logout_user

from .. import bcrypt,mail
from ..forms import RegistrationForm, LoginForm, UpdateUsernameForm
from ..models import User, Playlist
import io
import base64
import os

users = Blueprint("users", __name__)

@users.route("/register", methods=["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for("songs.index"))

    form = RegistrationForm()
    if form.validate_on_submit():
        hashed = bcrypt.generate_password_hash(form.password.data).decode("utf-8")
        user = User(username=form.username.data, email=form.email.data, password=hashed)
        msg = Message("Thank you for registering an account on Playlist Manager", sender = "noreply@gmail.com", recipients=[form.email.data])
        mail.send(msg)
        user.save()
        

        return redirect(url_for("users.login"))

    return render_template("register.html", title="Register", form=form)


@users.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("songs.index"))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.objects(username=form.username.data).first()

        if user is not None and bcrypt.check_password_hash(
            user.password, form.password.data
        ):
            login_user(user)
            return redirect(url_for("users.account"))
        else:
            flash("Login failed. Check your username and/or password")
            return redirect(url_for("users.login"))

    return render_template("login.html", title="Login", form=form)


@users.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for("playlist.index"))


@users.route("/account", methods=["GET", "POST"])
@login_required
def account():
    username_form = UpdateUsernameForm()

    if username_form.validate_on_submit():
        # current_user.username = username_form.username.data
        current_user.modify(username=username_form.username.data)
        current_user.save()
        return redirect(url_for("users.account"))

    return render_template(
        "account.html",
        title="Account",
        username_form=username_form,
    )


@users.route("/user/<username>", methods=["GET"])
def user_detail(username):
    user = User.objects(username=username).first()
    playlists = Playlist.objects(author=user)
    favorites = user.favorites
    count = len(favorites)
    return render_template("user_detail.html", username=username, playlists=playlists, favorites=favorites, count = count)

def get_b64_img(username):
    user = User.objects(username = username).first()
    bytes_im = io.BytesIO(user.profile_pic.read())
    image = base64.b64encode(bytes_im.getvalue()).decode()
    return image

app/templates/account.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h1>Hey, {{ current_user.username }}!</h1>
    </div>
</div>
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ username_form.csrf_token }}
            <div class="form-group">
                {{ username_form.username.label(class="form-control-label") }}
                {{ username_form.username(class="form-control form-control-lg") }}

                {% if username_form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in username_form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group py-3">
                {{ username_form.submit(class="btn btn-outline-success") }}
            </div>
        </form>
    </div>
</div>
<a href="{{ url_for('users.user_detail', username=current_user.username) }}" class="btn btn-outline-secondary">Your Playlists</a>
{% endblock %}>

app/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://bootswatch.com/5/vapor/bootstrap.min.css" crossorigin="anonymous">
     <link rel="stylesheet" href="{{ url_for('static', filename='custom.css') }}">
    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>Playlist Manager</title>
    {% endif %}
</head>
<body>
    {% block header %}
    <h1>Overrideable Content</h1>
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

app/templates/create_playlist.html
{% extends "header.html" %}
{% block content %}

{% if current_user.is_authenticated %}
{# Movie review submission form #}
<div class="row">
  <div class="col">
    <form method="POST" action="">
      {{ form.csrf_token }}
      <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}

        {% if form.title.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.title.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}
      </div>

      <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="form-control") }}

        {% if form.description.errors %}
        <div class="alert alert-warning" role="alert">
          {% for error in form.description.errors %}
          <span>{{ error }}</span>
          {% endfor %}
        </div>
        {% endif %}
      </div>

      {{ form.submit() }}
    </form>
  </div>
</div>
{% endif %}

{% endblock %}

app/templates/edit_playlist.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="mx-auto py-3">
        <h2>Use the search bar to add songs to this playlist.</h2>
    </div>

    <div class="mx-auto py-3">
        <form class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            <br>

            {{ form.submit(class="btn btn-outline-success") }}
        </form>

        <div class="mx-auto py-3">

             <a href="{{url_for('playlist.playlist_detail', playlist_id=playlist_id)}}" class="btn btn-outline-secondary">Return to Playlist</a>

        </div>
       
    </div>
</div>
{% endblock %}

app/templates/header.html
{% extends "base.html" %}
{% block header %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand px-3" href="{{ url_for('playlist.index') }}">Playlist Manager</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0 px-3">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.account') }}">
                    Account
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">
                    Logout
                </a>
            </li>
            <li class="nav-item">
                <a class="btn btn-primary" href="{{ url_for('playlist.create') }}">Create Playlist</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">
                    Login
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.register') }}">
                    Register
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% block content %}{% endblock %}
</div>
{% endblock %}

app/templates/index.html
{% extends "header.html" %}
{% block content %}

<div class="row">
    <div class="mx-auto py-3">
        <h2>Use the search bar to find user created playlists.</h2>
    </div>

    <div class="mx-auto py-3">
        <form action="/" class="form-inline my-2 my-lg-0" method="POST">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}

            {{ form.csrf_token }}
            {{ form.search_query(class="form-control", placeholder="Search") }}

            {% if form.search_query.errors %}
            <div class="alert alert-warning" role="alert">
                {% for error in form.search_query.errors %}
                <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}

            <br>

            {{ form.submit(class="btn btn-outline-success") }}
        </form>
    </div>
</div>
{% endblock %}

app/templates/login.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Log In</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you <b>don't</b> have an account, then <a href="{{ url_for('users.register') }}">Register!</a>
    </div>
</div>
<div class="row">
    <div class="col">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        {% for message in messages %}
        <div class="alert alert-info">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label green-text") }}
                {{ form.username(class="form-control form-control-md") }}

                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}

                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/playlist_detail.html
{% extends "header.html" %}
{% block content %}


{% if playlist %}

{# Display card for the movie details #}
<div class="row">
  <div class="col">
    <div class="card text-center">
      <div class="card-header">
        {{ playlist.title }}
      </div>
      <div class="card-body">
        <ul class="list-group list-group-flush">
          <li class="list-group-item"><b>Created by:</b> <a class="nav-link" href="{{url_for('users.user_detail',username=playlist.author.username) }}">{{playlist.author.username }}</a></li>
          <li class="list-group-item"><b>Description:</b> {{ playlist.description }}</li>
          <li class="list-group-item"><b>Created On:</b> {{ playlist.date }}</li>
          <li class="list-group-item"><b>Number Of Songs:</b> {{ count }}</li>
          <li class="list-group-item"><b>Playlist Duration:</b> {{ playlist.get_duration() }}</li>
        </ul>
      </div>
    </div>
  </div>
</div>

{# Songs #}
<div class="row">
  <div class="col-md-12 py-3">
    <h1> Songs </h1>
    <div class="py-3">
      {% for song in playlist.songs %}
        <img src="{{ song.image }}" alt="missing">
        <div class="media-body py-3">
            <h5 class="mt-0">{{ song.title }}  - {{ song.artist }}</h5>
        </div>
      {% endfor %}
    </div>
      
  </div>
</div>

{% if current_user.is_authenticated %}
{# Favorite Playlist Form#}
<div class="row py-3">
  <div class="col">
    <form method="POST" action="">
      {{ favorite.csrf_token }}
      {{ favorite.submit(class="btn btn-outline-secondary") }}
    </form>
  </div>
</div>
{% endif %}
{% endif %}
{% endblock content %}

app/templates/playlistquery.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <div class="media-body">
        <h5 class="mt-0"><a href="{{ url_for('playlist.playlist_detail', playlist_id=result.id) }}">{{ result.title }}</a> 
            <a href = "{{ url_for('users.user_detail', username = result.author.username)}}">{{ result.author.username }}</a></h5>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/query.html
{% extends "header.html" %}
{% block content %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

<div class="container-fluid">
    {% for result in results %}
    <div class="media">
        <img src="{{ result.image }}" alt="missing">
        <div class="media-body py-3">
            <h5 class="mt-0">{{ result.title }}  - {{ result.artist }}</h5>
            <form>
                <a href="{{ url_for('playlist.add_song', playlist_id=playlist_id, song_id=result.id)}}" class="btn btn-outline-success">Add Song</a>
            </form>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

app/templates/register.html
{% extends "header.html" %}
{% block content %}
<div class="row">
    <div class="col">
        <h2>Registration</h2>
    </div>
</div>
<div class="row">
    <div class="col">
        If you already have an account, then just <a href="{{ url_for('users.login') }}">Log In!</a>
    </div>
</div>
<!-- Registration Form: -->
<div class="row">
    <div class="col">
        <form action="" method="post">
            {{ form.csrf_token }}
            <div class="form-group">
                {{ form.username.label(class="form-control-label") }}
                {{ form.username(class="form-control form-control-lg") }}
                {% if form.username.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label") }}
                {{ form.email(class="form-control form-control-lg") }}
                {% if form.email.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label") }}
                {{ form.password(class="form-control form-control-lg") }}
                {% if form.password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label") }}
                {{ form.confirm_password(class="form-control form-control-lg") }}
                {% if form.confirm_password.errors %}
                <div class="alert alert-warning" role="alert">
                    {% for error in form.confirm_password.errors %}
                    <span>{{ error }}</span>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.submit(class="form-control form-control-lg") }}
            </div>
        </form>
    </div>
</div>

{% endblock %}

app/templates/user_detail.html
{% extends "header.html" %}
{% block content %}


<div class="row">
    <div class="col">
        <h1> Created Playlists <small class="float-right">{{ playlists.count() }} playlists</small></h1>
        <ul class="media-list">
            {% for playlist in playlists %}
            <li class="media review-item">
                <div class="media-body py-3">
                    <strong><a href="{{ url_for('playlist.playlist_detail', playlist_id=playlist.id) }}">
                        {{ playlist.title }}
                    </a>
                    </strong>
                    <span class="float-right">
                        <small>{{ playlist.date }}</small>
                    </span>
                    
                    <a href="{{ url_for('playlist.edit_playlist', playlist_id=playlist.id)}}" class="btn btn-info" role="button">Edit Playlist</a>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
<div class="row">
    <div class="col">
        <h1> Favorite Playlists <small class="float-right">{{count}} playlists</small></h1>
        <ul class="media-list">
            {% for playlist in favorites %}
            <li class="media review-item">
                <div class="media-body">
                    <strong><a href="{{ url_for('playlist.playlist_detail', playlist_id=playlist.id) }}">
                        {{ playlist.title }}
                    </a>
                    </strong>
                    <span class="float-right">
                        <small>{{ playlist.date }}</small>
                    </span> 
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}